#!/bin/bash 

function compress {
    brass data/$1.txt data/$1.bin
    data/lz48 -i data/$1.bin -o data/$1.binlz
    rm data/$1.bin
}

if [ -z "$1" ]; then
    compress title
    compress end
    compress lvl1
    compress lvl2
    compress lvl3
    compress lvl4
fi

#
# the compressed data files are always checked in to git,
# so there's no need to build them unless changed.
#
# if building on PC all you need is the following line:
brass -s biggoil.asm biggoil.com -l bote.html

cp biggoil.com ../mame/bo
